import {fileURLToPath} from 'node:url';
import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
const root=path.dirname(fileURLToPath(import.meta.url));const m=JSON.parse(await fs.readFile(root+'/manifesto.json','utf8'));const missing=[],external=[],hashErrors=[],empty=[],decodeErrors=[];let refs=0;
async function check(ref,from,kind){if(!ref||/^(?:#|data:|javascript:|mailto:|tel:|blob:)/i.test(ref))return;if(/^(https?:)?\/\//.test(ref)){external.push({from,kind,url:ref});return;}let file;try{file=decodeURIComponent(ref.replace(/&amp;/g,'&').split(/[?#]/)[0]);}catch{return;}const resolved=path.resolve(root,path.dirname(from),file);refs++;try{await fs.access(resolved);}catch{missing.push({from,kind,ref});}}
for(const f of m.files.filter(f=>!f.error)){
 const b=await fs.readFile(root+'/'+f.path);if(!b.length)empty.push(f.path);if(crypto.createHash('sha256').update(b).digest('hex')!==f.localSha256)hashErrors.push(f.path);
 if(f.path.endsWith('.html')){
 const h=b.toString();if(!h.includes('<html')||!h.includes('</html>')||/function\s+\w+\(\w+\)\{var\s+[\s\S]*?=Function/.test(h))decodeErrors.push(f.path);
 const raw=await fs.readFile(root+'/originais/'+f.path,'utf8');const fun=raw.match(/function\s+(\w+)\(\w+\)\{var\s+([\s\S]*?)for\(/);if(fun){const expected=[...raw.matchAll(new RegExp('\\b'+fun[1]+'\\(','g'))].length-1;const actual=[...raw.matchAll(new RegExp(String.raw`\b${fun[1]}\(((?:"(?:\\.|[^"\\])*"\s*\+?\s*)+)\);`,'g'))].length;if(expected!==actual)decodeErrors.push({path:f.path,expected,actual});}
 const markup=h.replace(/<!--[\s\S]*?-->/g,'').replace(/(<script\b[^>]*>)[\s\S]*?<\/script>/gi,'$1</script>');
 for(const t of markup.matchAll(/<(?:a|script|link|img|source|video|audio|iframe)\b[^>]*>/gi))for(const a of t[0].matchAll(/\b(src|href|poster)\s*=\s*(["'])(.*?)\2/gi))await check(a[3],f.path,a[1]);
 }else if(f.path.endsWith('.css'))for(const a of b.toString().replace(/\/\*[\s\S]*?\*\//g,'').matchAll(/\burl\(\s*["']?([^\s)'"<>]+)["']?\s*\)|@import\s+["']([^"']+)["']/gi))await check(a[1]||a[2],f.path,'css');
}
const report={verifiedAt:new Date().toISOString(),downloadedFiles:m.files.filter(f=>!f.error).length,htmlPages:m.files.filter(f=>f.path.endsWith('.html')&&!f.error).length,totalBytes:m.files.filter(f=>!f.error).reduce((a,f)=>a+f.bytes,0),referencesChecked:refs,missingLocalReferences:missing,hashErrors,emptyFiles:empty,decodingErrors:decodeErrors,remainingExternalReferences:external,collectionErrors:m.files.filter(f=>f.error),scope:'Links e recursos estáticos locais + integridade SHA-256. Não certifica serviços de negócio nem todas as interações das 180 telas.'};await fs.writeFile(root+'/verificacao.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,remainingExternalReferences:[...new Set(external.map(x=>x.url))]},null,2));
